/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CustomFileClass
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CustomFileClass = class extends import_obsidian.Plugin {
  async onload() {
  }
  async loadSettings() {
  }
  async saveSettings() {
  }
  onunload() {
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHsgUGx1Z2luIH0gZnJvbSAnb2JzaWRpYW4nO1xuXG5leHBvcnQgZGVmYXVsdCBjbGFzcyBDdXN0b21GaWxlQ2xhc3MgZXh0ZW5kcyBQbHVnaW4ge1xuXG5cdGFzeW5jIG9ubG9hZCgpOiBQcm9taXNlPHZvaWQ+XG5cdHtcblxuXHR9XG5cblx0Lypcblx0LS0tLS0tLS0tLS0tXG5cdFNldHRpbmdzXG5cdC0tLS0tLS0tLS0tLVxuXHQqL1xuXG5cdGFzeW5jIGxvYWRTZXR0aW5ncygpIHt9O1xuXG5cdGFzeW5jIHNhdmVTZXR0aW5ncygpIHt9O1xuXG5cdG9udW5sb2FkKCkge307XG59XG4iXSwKICAibWFwcGluZ3MiOiAiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUEsc0JBQXVCO0FBRXZCLElBQXFCLGtCQUFyQixjQUE2Qyx1QkFBTztBQUFBLEVBRW5ELE1BQU0sU0FDTjtBQUFBLEVBRUE7QUFBQSxFQVFBLE1BQU0sZUFBZTtBQUFBLEVBQUM7QUFBQSxFQUV0QixNQUFNLGVBQWU7QUFBQSxFQUFDO0FBQUEsRUFFdEIsV0FBVztBQUFBLEVBQUM7QUFDYjsiLAogICJuYW1lcyI6IFtdCn0K
